### PR TITLE
PHP 7.4 Compatibility

### PR DESCRIPTION
**Pull request by Rabee3Nassar**
We are getting those error after upgrading to PHP 7.4

1. preg_match_all(): Compilation failed: invalid range in character class at offset 4 in composer/vendor/paquettg/php-html-parser/src/PHPHtmlParser/Selector.php on line 91

Fixed by replacing:
`/([\w-:\*>]*)(?:\#([\w-]+)|\.([\w-]+))?(?:\[@?(!?[\w-:]+)(?:([!*^$]?=)[\"']?(.*?)[\"']?)?\])?([\/, ]+)/is`
with 
`/([\w\-:\*>]*)(?:\#([\w-]+)|\.([\w-]+))?(?:\[@?(!?[\w\-:]+)(?:([!*^$]?=)[\"']?(.*?)[\"']?)?\])?([\/, ]+)/is`

2. PHP Warning:  count(): Parameter must be an array or an object that implements Countable in composer/vendor/paquettg/php-html-parser/src/PHPHtmlParser/Selector.php on line 173

3. PHP Warning:  count(): Parameter must be an array or an object that implements Countable in composer/vendor/paquettg/php-html-parser/src/PHPHtmlParser/Selector.php on line 174

### CODE REVIEW

**Comment by skizzo** [comment]
Hi, any updates on this?

**Comment by paquettg** [comment]
Hey Skizzo,

Any version 3.0.X is currently working with php 7.4 and has been for a while now. Please upgrade to the most recent version.

Thank you.

**Comment by skizzo** [comment]
Aight, thanks for the info, and this amazing package in general :)
